# ベースイメージ
FROM python:3.11-slim
WORKDIR /workspace

# 依存関係だけ先にコピーしてキャッシュ効率を最大化 開発用の .dev.txtの方です
COPY ./infra/requirements.dev.txt /workspace/

# 依存環境ファイルインストール 開発用の .dev.txtの方です
RUN pip install --upgrade pip && pip install --no-cache-dir -r /workspace/requirements.dev.txt

# ローカルでbind mountするためCOPYは省略してもOK
# COPY ./app ./app

# compose.dev.ymlのCMD(command)で上書きされてしまうので、ここではコメントアウト
#CMD ["python", "-m", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]